### ISSUE TITLE
error with Node Sass 

### ISSUE THREAD

**Issue by sandrojj82** [ikismail/Angular-ShoppingCart#15]
Hi, I have the following error when compiling:

Error: Node Sass does not yet support your current environment: Windows 64-bit with Unsupported runtime (67) For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v4.9.3

try to solve changing the "node-sass" in the package.json to a lower version but it did not work, it does not work either "npm rebuild node-sass"

work with node v11.0.0
any ideas?

**Comment by ikismail** [comment]
try to delete node_modules
and run `npm install`

**Comment by ikismail** [comment]
This issue has been closed because there has been no response. With only the
  information that is currently in the issue, we don't have enough information
  to take action. Please reach out if you have or find the answers we need so
  that we can investigate further.
