### ISSUE TITLE
Where is the link for accessing admin to do CRUD for products?

### ISSUE THREAD

**Issue by kevintanhongann** [ikismail/Angular-ShoppingCart#16]
Where is the link for accessing admin to do CRUD for products?

I was digging the routing definitions and I didn't find the routes.

**Comment by ikismail** [comment]
@kevintanhongann there is no admin module, for creating or removing product you need to login as admin. Just go through the Step: 9 in [README Documentation](https://github.com/ikismail/Angular-ShoppingCart/blob/master/README.md)
