### ISSUE TITLE
Error: Callback was already called.

### ISSUE THREAD

**Issue by naruto523** [ikismail/Angular-ShoppingCart#3]
i run the command `ng serve` and i get this error 
`Error: Callback was already called.`

help me please

**Comment by jahanzaib76** [comment]
Getting this error

![image](https://user-images.githubusercontent.com/15321820/41700826-6fd408e8-7543-11e8-84f8-72f2dcc2f6aa.png)
****

**Comment by ikismail** [comment]
Thanks for reporting this. Looks like it's something to do with what module versions are installed.
What I mean by that is that if you install with yarn you wont see this issue since yarn is a bit better at handling modules and modules within modules.

So as a work around: use yarn instead.
