### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by thecodinggeek12** [ikismail/Angular-ShoppingCart#36]
How have you filtered the product category wise? Can you explain please!

**Comment by ikismail** [comment]
@thecodinggeek12 sorry for the delay,

 Filtering products based on the product Brand.
![image](https://user-images.githubusercontent.com/17190913/50478253-3d814e80-09f6-11e9-940a-661d9c70acc7.png)

you can check out the code **filterByBrand Pipe** [here](https://github.com/ikismail/Angular-ShoppingCart/blob/master/src/app/shared/pipes/filterByBrand.pipe.ts)
