### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by AKhileshPothuri** [ikismail/Angular-ShoppingCart#50]
The login page doesn't direct to the product page after a successful login bu still stays on login page .

**Comment by ikismail** [comment]
Can u check the console whether getting any errors or not. If yes kindly share the screenshot here. so that It will be easy for me to debug. Thanks @AKhileshPothuri

**Comment by AKhileshPothuri** [comment]
Hey..! The issue is resolved ..thankyou
