### ISSUE TITLE
How to create a location search box with suggestions 

### ISSUE THREAD

**Issue by akhilrajarj** [ikismail/Angular-ShoppingCart#53]
Hi I'm working on a Assignment and I'm supposed to create a location search box with suggestions .on pressing enter the text box should be cleared and the entered data should be displayed below.
Could you please help me with this.

I've attached an sample image
![assignment](https://user-images.githubusercontent.com/42715093/64616828-ef34a400-d3fa-11e9-9aca-f5230adc73c7.png)

**Comment by ikismail** [comment]
Here is a simple demo implemented using React [jsFiddle](https://jsfiddle.net/ikismail7/dyg9Lxre/2/)

**Comment by akhilrajarj** [comment]
Thank you.
