### ISSUE TITLE
Npm installaton isue

### ISSUE THREAD

**Issue by aslamsk** [ikismail/Angular-ShoppingCart#58]
i am trying to install npm but getting error

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! grpc@1.16.0 install: `node-pre-gyp install --fallback-to-build --library=static_library`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the grpc@1.16.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

**Comment by ikismail** [comment]
This issue has been closed because there has been no response. With only the
information that is currently in the issue, we don't have enough information
to take action. Please reach out if you have or find the answers we need so
that we can investigate further.
