### ISSUE TITLE
Firebase error.

### ISSUE THREAD

**Issue by jahanzaib76** [ikismail/Angular-ShoppingCart#6]
![image](https://user-images.githubusercontent.com/15321820/41700861-8b873d44-7543-11e8-9df5-dd47b5d7a6bf.png)

**Comment by ikismail** [comment]
Hi @jahanzaib76 you just want to configure with your firebase API [installation link](https://github.com/ikismail/Angular-ShoppingCart#installation)

Reference Link: [Creating Firbease App and Setup](https://medium.com/codingthesmartway-com-blog/building-an-angular-5-project-with-bootstrap-4-and-firebase-4504ff7717c1)
