### ISSUE TITLE
Possibilty to make the page wider

### ISSUE THREAD

**Issue by Kuncy** [ikismail/Angular-ShoppingCart#64]
Hi, how is it possible to make the page wider? There are white bars on the left and right from the page.
Cant find the place to change it.

Thanks in advice.

**Comment by ikismail** [comment]
Yes, you can make the page wider.

you can change the container class here [index.component.html#L2](https://github.com/ikismail/Angular-ShoppingCart/blob/master/src/app/views/base/index/index.component.html#L2)

Reference: 
- [Bootstrap Containers](https://getbootstrap.com/docs/4.5/layout/overview/#containers)

**Comment by Kuncy** [comment]
Thanks alot, already found that part but wasnt sure.  :)
