### ISSUE TITLE
[BUG] Firebase fatal error

### ISSUE THREAD

**Issue by quyenhair2109** [ikismail/Angular-ShoppingCart#67]
I clone ur code and run 'ng serve' and then it had the error on the console like this: 
[2020-08-22T10:39:51.853Z]  @firebase/database: FIREBASE FATAL ERROR: Cannot parse Firebase url. Please use https://<YOUR FIREBASE>.firebaseio.com 
and it showed me on the problem on this code:
var defaultLogHandler = function (instance, logType) {
    var args = [];
    for (var _i = 2; _i < arguments.length; _i++) {
        args[_i - 2] = arguments[_i];
    }
    if (logType < instance.logLevel) {
        return;
    }
    var now = new Date().toISOString();
    var method = ConsoleMethod[logType];
    if (method) {
        console[method].apply(console, __spreadArrays(["[" + now + "]  " + instance.name + ":"], args)); // particularly in this line
    }
    else {
        throw new Error("Attempted to log a message with an invalid logType (value: " + logType + ")");
    }
};
Do sb know what wrong with the code I clone or my set up???
Thank you.

**Comment by Kuncy** [comment]
I think you dont paste your firebase configuration, look into the installtion guide ->

8. Configure your firebase configuration src/environments/firebaseConfig.ts

**Comment by ikismail** [comment]
you just want to configure with your firebase API [installation link](https://github.com/ikismail/Angular-ShoppingCart#installation)

Reference Link: [Creating Firbease App and Setup](https://medium.com/codingthesmartway-com-blog/building-an-angular-5-project-with-bootstrap-4-and-firebase-4504ff7717c1)

_Originally posted by @ikismail in https://github.com/ikismail/Angular-ShoppingCart/issues/6#issuecomment-398988688_
