### ISSUE TITLE
Question about use updateProduct()

### ISSUE THREAD

**Issue by Logan0official** [ikismail/Angular-ShoppingCart#68]

**Comment by ikismail** [comment]
> updateProduct(data: Product) {
> this.products.update(data.$key, data);
> }
> I noticed this but still did not understand how to use it?

@Logan0official  Can u please elaborate the question!

**Comment by Logan0official** [comment]
You have indicated that the admin can edit the product. As I understand it, it is connected somehow, but nowhere is it applied. And I can't figure it out a bit.

**Comment by Logan0official** [comment]
I don't understand how to edit a product. Since the description indicates what is possible. But no matter how I understand there, only adding a new one. And there is no editing.
