### ISSUE TITLE
I can't get products

### ISSUE THREAD

**Issue by ozmenahmetcan** [ikismail/Angular-ShoppingCart#76]
How can I call products?  (And what should I do to change the route names I need to turn this site into a car site)

![Screenshot_2](https://user-images.githubusercontent.com/75603082/210606798-cdd86ed3-4a4a-4974-8b2b-5ae53a5c1c8b.png)
![Screenshot_3](https://user-images.githubusercontent.com/75603082/210606921-8901228d-9967-42a9-9a7e-961a19099518.png)

**Comment by ikismail** [comment]
Hi @ozmenahmetcan, I have updated the document to import the products to your firebase database.
